2 desarrollar contexto empleados
Mercap/okr-frontend pull request #42
Opened 2019-05-28 16:20 UTC by ezeBalsamo

people context development and tests

2019-05-29 02:26 UTC, apiorno requested changes

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		assert: ( context removePerson: '15' )
Yo guardaría eso en una variable "response" para que quede mas claro que es devolvió algo

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		equals: ( NeoJSONObject fromString: self deletePersonJSONResponse )
Quedaría más lindo un extract de eso que recibe el equals:

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +	self assert: context people equals: ( NeoJSONObject fromString: self getPeopleJSONResponse )
Lo mismo de antes

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +	self assert: person equals: ( NeoJSONObject fromString: self getPersonByIDJSONResponse )
Lo mismo para la parte del equals:

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		assert: ( context addPerson: self person )
mismo

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		equals: ( NeoJSONObject fromString: self postPersonJSONResponse )
mismo

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		assert: ( context updatePerson: person )
mismo

2019-05-29 02:26 UTC, apiorno commented on source/People-Views-Tests/PeopleContextTest.class.st
> +		equals: ( NeoJSONObject fromString: ( self jsonFor: person ) )
lo mismo

2019-05-29 02:49 UTC, marcodicro requested changes

2019-05-29 02:49 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +	^'http://example.com'
Llevar baseUrl al ApplicationContext

2019-05-29 02:49 UTC, marcodicro commented on source/People-Views/Person.class.st
> +	#name : #Person,
Para qué esta clase si no hay validaciones de modelo?

2019-05-29 02:49 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +PeopleContext >> post: anUrl containing: aPerson [
anUrl no se usa. eliminar colaborador

2019-05-29 02:49 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +		ifFalse: [ HttpRequestDidNotSucceed signal: 'hubo un problema con la conexión' ]
Pueden utilizar el contenido de la response para informar un error mas especifico

2019-05-29 02:49 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +	^ self post: self peopleUrl containing: aPerson
Este extract no hace falta

2019-05-29 02:52 UTC, apiorno commented on source/People-Views/PeopleContext.class.st
> +	^'http://example.com'
Esto no, porque la idea es que no se conozca al application context asi. Se debería llegar desde la sesión ( hay que agregar sesión nueva y lo estoy haciendo aparte)

2019-05-29 14:04 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +	^'http://example.com'
Ok después mostrame como quedaría

2019-06-08 19:52 UTC, marcodicro commented
@ezeBalsamo necesitas ayuda con esto??

2019-06-11 21:36 UTC, marcodicro approved these changes

2019-06-11 21:36 UTC, marcodicro commented on source/People-Views/PeopleContext.class.st
> +PeopleContext >> removePerson: aPersonUUID [
esperaría que esto reciba como colaborador un objecto Person como el add y el update

2019-06-11 21:36 UTC, marcodicro commented on source/People-Views/Person.class.st
> +	#name : #Person,
Se deja asi para mergear

2019-06-12 19:41 UTC, apiorno approved these changes

2019-06-12 19:41 UTC, merged