32 implement teams management view
Mercap/okr-frontend pull request #52
Opened 2019-06-02 05:55 UTC by apiorno

Vista para grupos, permite agregar y modificar con una misma view. Tambien se deja la opción de borrar. 
Se crea la session especifica para darle información extra ( Application) y poder acceder de manera global.
 Refactor de tests, se un truquito para emular el contexto de seaside y tener acceso a session que igual es mockeado en el testase

2019-06-02 15:58 UTC, marcodicro requested changes
Estaría bueno también que hagas el merge commit para que el review sea el final para poder mergear.

sino va a haber que hacer el review de nuevo

2019-06-02 15:58 UTC, marcodicro commented on source/OKR-Frontend/DashboardView.class.st
> +	| objectivesButton |
rename local variable

2019-06-02 15:58 UTC, marcodicro commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +	"Cambiar por (ZnClient new) cuando este lista la api -mdicroce"
De paso ya se puede sacar este comentario

2019-06-02 15:58 UTC, marcodicro commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +OKRFrontendApplicationContext >> objectivesJson [
esto ya no debería estar

2019-06-02 15:58 UTC, marcodicro commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +	self flag: 'Cambiar'.
que onda esto?

2019-06-02 15:58 UTC, marcodicro commented on source/Team-Views/TeamsContext.class.st
> +	^ ZnStringEntity json: json
probaste que funcione esto para el post? Porque te va a poner como mediaType "application/json"

2019-06-02 15:58 UTC, marcodicro commented on source/Team-Views/TeamsWebView.class.st
> +	^ '<1s> z2s> - <3s>' expandMacrosWith: aMember name with: aMember lastName with: aMember email
Creo que acá te quedó una z en vez de <

2019-06-06 01:25 UTC, apiorno commented on source/OKR-Frontend/DashboardView.class.st
> +	| objectivesButton |
Esto voló

2019-06-06 01:26 UTC, apiorno commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +	"Cambiar por (ZnClient new) cuando este lista la api -mdicroce"
Done

2019-06-06 01:26 UTC, apiorno commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +OKRFrontendApplicationContext >> objectivesJson [
Done

2019-06-06 01:26 UTC, apiorno commented on source/OKR-Frontend/OKRFrontendApplicationContext.class.st
> +	self flag: 'Cambiar'.
No se, pero voló

2019-06-06 01:27 UTC, apiorno commented on source/Team-Views/TeamsContext.class.st
> +	^ ZnStringEntity json: json
No hay api real, mockee una y no me tiró nada. Igual ya lo agregué

2019-06-06 01:27 UTC, apiorno commented on source/Team-Views/TeamsWebView.class.st
> +	^ '<1s> z2s> - <3s>' expandMacrosWith: aMember name with: aMember lastName with: aMember email
Si, ya lo arreglé

2019-06-06 01:28 UTC, apiorno commented
> Estaría bueno también que hagas el merge commit para que el review sea el final para poder mergear.
> 
> sino va a haber que hacer el review de nuevo

Ya integré con release-candidate, pero hice mucho refactor

2019-06-06 13:51 UTC, marcodicro commented
> > Estaría bueno también que hagas el merge commit para que el review sea el final para poder mergear.
> > sino va a haber que hacer el review de nuevo
> 
> Ya integré con release-candidate, pero hice mucho refactor

Todavía me aparece como que hay merge conflict. Solucionalo asi hago el review de eso y de tus refactors

2019-06-06 23:18 UTC, apiorno commented
> > > Estaría bueno también que hagas el merge commit para que el review sea el final para poder mergear.
> > > sino va a haber que hacer el review de nuevo
> > 
> > 
> > Ya integré con release-candidate, pero hice mucho refactor
> 
> Todavía me aparece como que hay merge conflict. Solucionalo asi hago el review de eso y de tus refactors

Va a seguir habiendo porque cambie paquetes y todo. Hay que resolverlo aca. Además el review es siempre previo al merge, es lo normal que haya merge conflicts. Lo mergeo yo y listo

2019-06-08 19:49 UTC, marcodicro submitted a review, later dismissed

2019-06-08 19:49 UTC, marcodicro commented on source/OKR-Frontend/OKRFrontendApplication.class.st
> +	^ 'http://localhost:1710'
esto creo que hay que volarlo

2019-06-08 23:56 UTC, apiorno commented on source/OKR-Frontend/OKRFrontendApplication.class.st
> +	^ 'http://localhost:1710'
No, porque el "applicationContext" de la session es la Application, porque los contextos no existen todavía

2019-06-09 02:41 UTC, marcodicro commented
Y entonces por qué hay otra implementación de base path en el context? Esa si vuela?

El 8 jun. 2019 8:56 p. m., Alvaro Piorno <notifications@github.com> escribió:

@apiorno commented on this pull request.

________________________________

In source/OKR-Frontend/OKRFrontendApplication.class.st<https://github.com/Mercap/okr-frontend/pull/52#discussion_r291822835>:

> +{ #category : #accessing }

+OKRFrontendApplication class >> handlerName [

+

+       ^'okr-frontend'

+]

+

+{ #category : #accessing }

+OKRFrontendApplication class >> sessionClass [

+

+       ^ OKRFrontendSession

+]

+

+{ #category : #accessing }

+OKRFrontendApplication >> basePath [

+

+       ^ 'http://localhost:1710'



No, porque el "applicationContext" de la session es la Application, porque los contextos no existen todavía

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/Mercap/okr-frontend/pull/52?email_source=notifications&email_token=AC4HGGZRK23656TYC7424RTPZRBJLA5CNFSM4HSB6FP2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB27M4MA#discussion_r291822835>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AC4HGG656DPL5MB6XVIK7V3PZRBJLANCNFSM4HSB6FPQ>.

2019-06-12 19:26 UTC, marcodicro submitted a review, later dismissed

2019-06-12 21:09 UTC, marcodicro requested changes

2019-06-12 21:09 UTC, marcodicro commented on source/Team-Views/TeamsWebView.class.st
> +applying: aComponentCommand
esta linea no va me parece @apiorno

2019-06-12 21:09 UTC, marcodicro commented on source/Team-Views/TeamsWebView.class.st
> +applying: aComponentCommand
te debe haber quedado de la definicion del metodo en la otra rama cuando hiciste el merge

2019-06-13 13:56 UTC, marcodicro approved these changes

2019-06-13 13:56 UTC, merged